### PR TITLE
Create spelling workflow

### PR DESCRIPTION
**Pull request by szepeviktor**
# Description

Fulfill wish in #775

## Type of change

- [x] CI (any automation pipeline changes)

### CODE REVIEW

**Review by steebchen — APPROVED** [review]
just needs a fix for the remaining typos, once fixed we can merge, thx!

**Comment by szepeviktor** [comment]
> the remaining typos,

I see a big green checkmark.

image

**Comment by steebchen** [comment]
yep I just merged main into your branch, so it is fixed now!

**Comment by szepeviktor** [comment]
Very Glad to contribute.

**Pull request merged**
