### PR TITLE
Copy to clipboard

### PR DESCRIPTION
**Pull request by badex-ai**
# Description
added the clipboardjs package for copying text from the props of the copy-to-clipboard.tsx file. I am not sure if that will fix the issue as a comment on the issues page states that a certain part of the package is said to be deprecated.

clipboardjs

Fixes # (issue)
#295 
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

## What's Changed
added the clipboardjs package for copying as stated by the issue.

- [ ] Add a list of tasks or features here...

### CODE REVIEW

**Comment by abelanger5** [comment]
Hey @badex-ai, thanks for the PR! I think we're in the same boat as Gitlab here: https://gitlab.com/gitlab-org/gitlab/-/issues/444197 - I wouldn't want us to rely on deprecated APIs, so perhaps we can just hide the button when we don't have access to `navigator.clipboard`?

**Comment by abelanger5** [comment]
To clarify, I thought clipboardjs was more up-to-date but haven't used it for a while.

**Comment by badex-ai** [comment]
@abelanger5, Thank you for replying, it strengthens my faith in contributing. Should I close the PR?

**Comment by abelanger5** [comment]
Yes, I'll close this PR. If you'd like to make a new PR which simply hides the button when the clipboard methods aren't available, we could definitely merge that!

**Pull request closed without merging**
